version: '3.1'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=Bjpv@1982
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:      
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    
volumes:
  esdata: